
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxpzjehudconqpjobkxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94cHpqZWh1ZGNvbnFwam9ia3hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NzYyNzAsImV4cCI6MjA2MzI1MjI3MH0.jkFShmvZ4SaEcXPtnfLqmR4oIjdBpDRL8BqiIyMlqyA";

// Create a Supabase client with proper configuration
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: localStorage
  }
});

// Helper to get data with error handling
export async function fetchDataFromApi<T>(
  queryFn: () => Promise<{ data: T | null; error: any }>
): Promise<T> {
  const { data, error } = await queryFn();
  
  if (error) {
    console.error("API Error:", error);
    throw new Error(`API Error: ${error.message}`);
  }
  
  if (!data) {
    throw new Error("No data returned from API");
  }
  
  return data;
}
